### ISSUE TITLE
How to close the opened Pickers?

### ISSUE THREAD

**Issue by Stan92** [ale84/ALEInlineDatePickerViewController#1]
Hello Alessio,
Thanks for sharing your controller.
Just a question, how can I close the opened pickers.
If I leave a view with an opened Picker, and I back to this view, I would like it comes with not opened pickers?
Could you please show me the direction?
Thanks

**Comment by ale84** [comment]
I modified the view controller, now you can hide the picker programmatically by calling hideExistingPicker on the view controller

**Comment by Stan92** [comment]
Thanks a lot....

**Comment by Stan92** [comment]
It seems you forget to add the controllers in your test project.

**Comment by ale84** [comment]
fixed

**Comment by Stan92** [comment]
works fine.. Thanks...
