### ISSUE TITLE
Setting Minimum / Maximum date

### ISSUE THREAD

**Issue by JulesMoorhouse** [ale84/ALEInlineDatePickerViewController#2]
Hi,

Whats going to be the best way to set the minimum and maximumdate date?

I'm guessing exposing the date picker as a property ?

EDIT: Actually I'm a bit lost with the code, even to add two date properties.
EDIT2: Hmm, guess I'll need some extra set date methods, bit lost.

Jules.

**Comment by ale84** [comment]
You can customize the date picker by overriding the `createDatePickerCell:` method and call super to get the picker cell, then you can access the datePicker property of the cell.

See the example project for how to have multiple pickers to the tableview.
To set the date for a particular row, use the `setDate: forIndexPath:` method, passing the indexPath for the row.
