### ISSUE TITLE
Min Date/Max Date

### ISSUE THREAD

**Issue by Stan92** [ale84/ALEInlineDatePickerViewController#3]
Hi ale84,
I read your answer (https://github.com/ale84/ALEInlineDatePickerViewController/issues/2).
But I can't figure out how to overriding the class? :-(

**Comment by ale84** [comment]
you have to override this method in your subclass of ALEInlineDatePickerViewController 

```
- (ALEDatePickerCell *)createPickerCell:(NSDate *)date
{
    ALEDatePickerCell *pickerCell = [super createPickerCell:date];
    pickerCell.datePicker.minimumDate = [NSDate date];
    return pickerCell;
}
```

**Comment by Stan92** [comment]
In fact the part that I didn't understand is "and call super to get the picker cell, then you can access the datePicker property of the cell."
My goal is to set a minimum date to the picker..
Sorry for the newbie question.
